from abc import ABC, abstractmethod

from flask import Request, Response


class ProxyInterface(ABC):
    """Proxy interface used as an intermediary between users and chatbot services."""

    @abstractmethod
    def handle_request(self, user_request: Request) -> Response:
        """
        Manage queries submitted by users.

        :param user_request: The query submitted by the user.
        :return: The response generated by the messages.
        """
        pass
